version: '3'

services:

  server:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "${SERVER_PORT}:3001"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development

  client:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
