version: '3' # Spécifie la version de Docker Compose utilisée.

services: # Définit les services modifiés ou ajoutés pour le mode production.

  server: # Configuration pour le service "server" en mode production.
    build: # Construit une image à partir d'un Dockerfile spécifique pour la production.
      dockerfile: ./Dockerfile.prod # Emplacement du Dockerfile pour la production.
    ports:
      - "${SERVER_PORT}:3001" # Mappe le port 3001 du serveur à une variable d'environnement sur l'hôte.
    environment: # Variables d'environnement spécifiques au mode production.
      - NODE_ENV=production

  client: # Configuration pour le service "client" (React) en mode production.
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - "127.0.0.1:${CLIENT_PORT}:80" # Mappe le port 80 du client React à une variable d'environnement sur l'hôte, accessible uniquement depuis l'hôte local.
    environment:
      - NODE_ENV=production
