version: '3'

services:

  server:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - "${SERVER_PORT}:3001"
    environment:
      - NODE_ENV=production

  client:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - "127.0.0.1:${CLIENT_PORT}:80"
    environment:
      - NODE_ENV=production
