metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: false
    period: 10s
    hosts: http://elasticsearch:9200

  - module: logstash
    xpack.enabled: false
    period: 10s
    hosts: http://logstash:5000

  - module: kibana
    xpack.enabled: false
    metricsets:
      - stats
    period: 10s
    hosts: http://kibana:5601

  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
